# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import audio_service_pb2 as protos_dot_audio__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/audio_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPredict = channel.stream_stream(
                '/ai.AudioClassifier/StreamPredict',
                request_serializer=protos_dot_audio__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=protos_dot_audio__service__pb2.PredictResponse.FromString,
                _registered_method=True)


class AudioClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPredict(self, request_iterator, context):
        """Bidirectional streaming: client sends AudioChunk stream, server replies with PredictResponse stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=protos_dot_audio__service__pb2.AudioChunk.FromString,
                    response_serializer=protos_dot_audio__service__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AudioClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AudioClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai.AudioClassifier/StreamPredict',
            protos_dot_audio__service__pb2.AudioChunk.SerializeToString,
            protos_dot_audio__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
