# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/audio_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/audio_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/audio_service.proto\x12\x02\x61i\"f\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\x12\x12\n\nsession_id\x18\x05 \x01(\x03\"^\n\x0fPredictResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x12\n\nsession_id\x18\x04 \x01(\x03\x32K\n\x0f\x41udioClassifier\x12\x38\n\rStreamPredict\x12\x0e.ai.AudioChunk\x1a\x13.ai.PredictResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.audio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=34
  _globals['_AUDIOCHUNK']._serialized_end=136
  _globals['_PREDICTRESPONSE']._serialized_start=138
  _globals['_PREDICTRESPONSE']._serialized_end=232
  _globals['_AUDIOCLASSIFIER']._serialized_start=234
  _globals['_AUDIOCLASSIFIER']._serialized_end=309
# @@protoc_insertion_point(module_scope)
